name = "idea-turbo-sync"
main = "./src/server.ts"
compatibility_date = "2026-01-06"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "idea-turbo-db"
database_id = "273ae549-6363-4cfc-b946-a80488cff63f"

