// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/memory/data/models/memory_entity.dart';
import 'features/memory/data/models/raw_message_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6773016212286002508),
    name: 'MemoryEntity',
    lastPropertyId: const obx_int.IdUid(31, 3010145431378643102),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7860537377876441270),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5608004516034708122),
        name: 'uid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8275118142972320538),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6047110506003149805),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1615238610660549487),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1159477362323884685),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 525981671725958866),
        name: 'importance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6525819981020484175),
        name: 'initialStrength',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6692574338693279432),
        name: 'strength',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8124716462966942285),
        name: 'emotionalValence',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1413589855659152124),
        name: 'surpriseScore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5710334732155726874),
        name: 'keywords',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7031219149373610550),
        name: 'entities',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1290277123948259923),
        name: 'topics',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 962553004115099221),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(3, 694537784553049337),
        hnswParams: obx_int.ModelHnswParams(dimensions: 256, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 6627265153757843114),
        name: 'encodingContextJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 5235178805540701843),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7546869244955577918),
        name: 'createdAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 8343550066181587773),
        name: 'accessedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 1004751646879406897),
        name: 'updatedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 6994319811856671112),
        name: 'accessCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 713412593410834180),
        name: 'sourceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 6681987079002186102),
        name: 'agentId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 9056798442643977851),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 2178225195617115824),
        name: 'relatedMemoryIds',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 2977965179277978222),
        name: 'parentMemoryId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 4241367483222164983),
        name: 'supersededById',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 3984403962985037102),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 4655172616666341158),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 3123191238083601791),
        name: 'isConsolidated',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 3010145431378643102),
        name: 'contentHash',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 48623085535412528),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1796791819879415904),
    name: 'RawMessageEntity',
    lastPropertyId: const obx_int.IdUid(10, 8758871504690148743),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3195381275055376908),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8255585083896079438),
        name: 'uid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7121352137924251513),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1437296113748404272),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8211266944772170542),
        name: 'speakerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3351329659532605432),
        name: 'petId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7396293245805287512),
        name: 'timestampMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3528138127737009924),
        name: 'isProcessed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7734607746800888686),
        name: 'processedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8758871504690148743),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1796791819879415904),
    lastIndexId: const obx_int.IdUid(4, 48623085535412528),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [8620475248495832367],
    retiredIndexUids: const [2265069103966236129],
    retiredPropertyUids: const [
      3615359794522839591,
      1342668161307358200,
      8413459363721986963,
      249296523948631717,
      5713966613264714718,
      98292326733833896,
      1847071067661988521,
      8097161094944528768,
      7757474439673293120,
      8143251517272286826,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MemoryEntity: obx_int.EntityDefinition<MemoryEntity>(
      model: _entities[0],
      toOneRelations: (MemoryEntity object) => [],
      toManyRelations: (MemoryEntity object) => {},
      getId: (MemoryEntity object) => object.obId,
      setId: (MemoryEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (MemoryEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final contentOffset = fbb.writeString(object.content);
        final typeOffset = fbb.writeString(object.type);
        final sourceOffset = fbb.writeString(object.source);
        final statusOffset = fbb.writeString(object.status);
        final keywordsOffset = fbb.writeString(object.keywords);
        final entitiesOffset = fbb.writeString(object.entities);
        final topicsOffset = fbb.writeString(object.topics);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final encodingContextJsonOffset = object.encodingContextJson == null
            ? null
            : fbb.writeString(object.encodingContextJson!);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        final sourceIdOffset = object.sourceId == null
            ? null
            : fbb.writeString(object.sourceId!);
        final agentIdOffset = object.agentId == null
            ? null
            : fbb.writeString(object.agentId!);
        final userIdOffset = object.userId == null
            ? null
            : fbb.writeString(object.userId!);
        final relatedMemoryIdsOffset = fbb.writeString(object.relatedMemoryIds);
        final parentMemoryIdOffset = object.parentMemoryId == null
            ? null
            : fbb.writeString(object.parentMemoryId!);
        final supersededByIdOffset = object.supersededById == null
            ? null
            : fbb.writeString(object.supersededById!);
        final contentHashOffset = fbb.writeString(object.contentHash);
        fbb.startTable(32);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, contentOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, sourceOffset);
        fbb.addOffset(5, statusOffset);
        fbb.addFloat64(6, object.importance);
        fbb.addFloat64(7, object.initialStrength);
        fbb.addFloat64(8, object.strength);
        fbb.addFloat64(9, object.emotionalValence);
        fbb.addFloat64(10, object.surpriseScore);
        fbb.addOffset(11, keywordsOffset);
        fbb.addOffset(12, entitiesOffset);
        fbb.addOffset(13, topicsOffset);
        fbb.addOffset(14, embeddingOffset);
        fbb.addOffset(15, encodingContextJsonOffset);
        fbb.addOffset(16, metadataJsonOffset);
        fbb.addInt64(17, object.createdAtMs);
        fbb.addInt64(18, object.accessedAtMs);
        fbb.addInt64(19, object.updatedAtMs);
        fbb.addInt64(20, object.accessCount);
        fbb.addOffset(21, sourceIdOffset);
        fbb.addOffset(22, agentIdOffset);
        fbb.addOffset(23, userIdOffset);
        fbb.addOffset(24, relatedMemoryIdsOffset);
        fbb.addOffset(25, parentMemoryIdOffset);
        fbb.addOffset(26, supersededByIdOffset);
        fbb.addBool(27, object.isPinned);
        fbb.addBool(28, object.isArchived);
        fbb.addBool(29, object.isConsolidated);
        fbb.addOffset(30, contentHashOffset);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final importanceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final initialStrengthParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final strengthParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final emotionalValenceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final surpriseScoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final keywordsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final entitiesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final topicsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final contentHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 64, '');
        final encodingContextJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final accessedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          40,
          0,
        );
        final updatedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        final accessCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final sourceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final agentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final relatedMemoryIdsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 52, '');
        final parentMemoryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 54);
        final supersededByIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 56);
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          58,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          60,
          false,
        );
        final isConsolidatedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          62,
          false,
        );
        final object = MemoryEntity(
          obId: obIdParam,
          uid: uidParam,
          content: contentParam,
          type: typeParam,
          source: sourceParam,
          status: statusParam,
          importance: importanceParam,
          initialStrength: initialStrengthParam,
          strength: strengthParam,
          emotionalValence: emotionalValenceParam,
          surpriseScore: surpriseScoreParam,
          keywords: keywordsParam,
          entities: entitiesParam,
          topics: topicsParam,
          embedding: embeddingParam,
          contentHash: contentHashParam,
          encodingContextJson: encodingContextJsonParam,
          metadataJson: metadataJsonParam,
          createdAtMs: createdAtMsParam,
          accessedAtMs: accessedAtMsParam,
          updatedAtMs: updatedAtMsParam,
          accessCount: accessCountParam,
          sourceId: sourceIdParam,
          agentId: agentIdParam,
          userId: userIdParam,
          relatedMemoryIds: relatedMemoryIdsParam,
          parentMemoryId: parentMemoryIdParam,
          supersededById: supersededByIdParam,
          isPinned: isPinnedParam,
          isArchived: isArchivedParam,
          isConsolidated: isConsolidatedParam,
        );

        return object;
      },
    ),
    RawMessageEntity: obx_int.EntityDefinition<RawMessageEntity>(
      model: _entities[1],
      toOneRelations: (RawMessageEntity object) => [],
      toManyRelations: (RawMessageEntity object) => {},
      getId: (RawMessageEntity object) => object.obId,
      setId: (RawMessageEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (RawMessageEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final contentOffset = fbb.writeString(object.content);
        final sourceOffset = fbb.writeString(object.source);
        final speakerIdOffset = object.speakerId == null
            ? null
            : fbb.writeString(object.speakerId!);
        final petIdOffset = object.petId == null
            ? null
            : fbb.writeString(object.petId!);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        fbb.startTable(11);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, contentOffset);
        fbb.addOffset(3, sourceOffset);
        fbb.addOffset(4, speakerIdOffset);
        fbb.addOffset(5, petIdOffset);
        fbb.addInt64(6, object.timestampMs);
        fbb.addBool(7, object.isProcessed);
        fbb.addInt64(8, object.processedAtMs);
        fbb.addOffset(9, metadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final speakerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final petIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final timestampMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final isProcessedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final processedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = RawMessageEntity(
          obId: obIdParam,
          uid: uidParam,
          content: contentParam,
          source: sourceParam,
          speakerId: speakerIdParam,
          petId: petIdParam,
          timestampMs: timestampMsParam,
          isProcessed: isProcessedParam,
          processedAtMs: processedAtMsParam,
          metadataJson: metadataJsonParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MemoryEntity] entity fields to define ObjectBox queries.
class MemoryEntity_ {
  /// See [MemoryEntity.obId].
  static final obId = obx.QueryIntegerProperty<MemoryEntity>(
    _entities[0].properties[0],
  );

  /// See [MemoryEntity.uid].
  static final uid = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[1],
  );

  /// See [MemoryEntity.content].
  static final content = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[2],
  );

  /// See [MemoryEntity.type].
  static final type = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[3],
  );

  /// See [MemoryEntity.source].
  static final source = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[4],
  );

  /// See [MemoryEntity.status].
  static final status = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[5],
  );

  /// See [MemoryEntity.importance].
  static final importance = obx.QueryDoubleProperty<MemoryEntity>(
    _entities[0].properties[6],
  );

  /// See [MemoryEntity.initialStrength].
  static final initialStrength = obx.QueryDoubleProperty<MemoryEntity>(
    _entities[0].properties[7],
  );

  /// See [MemoryEntity.strength].
  static final strength = obx.QueryDoubleProperty<MemoryEntity>(
    _entities[0].properties[8],
  );

  /// See [MemoryEntity.emotionalValence].
  static final emotionalValence = obx.QueryDoubleProperty<MemoryEntity>(
    _entities[0].properties[9],
  );

  /// See [MemoryEntity.surpriseScore].
  static final surpriseScore = obx.QueryDoubleProperty<MemoryEntity>(
    _entities[0].properties[10],
  );

  /// See [MemoryEntity.keywords].
  static final keywords = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[11],
  );

  /// See [MemoryEntity.entities].
  static final entities = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[12],
  );

  /// See [MemoryEntity.topics].
  static final topics = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[13],
  );

  /// See [MemoryEntity.embedding].
  static final embedding = obx.QueryHnswProperty<MemoryEntity>(
    _entities[0].properties[14],
  );

  /// See [MemoryEntity.encodingContextJson].
  static final encodingContextJson = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[15],
  );

  /// See [MemoryEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[16],
  );

  /// See [MemoryEntity.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<MemoryEntity>(
    _entities[0].properties[17],
  );

  /// See [MemoryEntity.accessedAtMs].
  static final accessedAtMs = obx.QueryIntegerProperty<MemoryEntity>(
    _entities[0].properties[18],
  );

  /// See [MemoryEntity.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<MemoryEntity>(
    _entities[0].properties[19],
  );

  /// See [MemoryEntity.accessCount].
  static final accessCount = obx.QueryIntegerProperty<MemoryEntity>(
    _entities[0].properties[20],
  );

  /// See [MemoryEntity.sourceId].
  static final sourceId = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[21],
  );

  /// See [MemoryEntity.agentId].
  static final agentId = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[22],
  );

  /// See [MemoryEntity.userId].
  static final userId = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[23],
  );

  /// See [MemoryEntity.relatedMemoryIds].
  static final relatedMemoryIds = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[24],
  );

  /// See [MemoryEntity.parentMemoryId].
  static final parentMemoryId = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[25],
  );

  /// See [MemoryEntity.supersededById].
  static final supersededById = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[26],
  );

  /// See [MemoryEntity.isPinned].
  static final isPinned = obx.QueryBooleanProperty<MemoryEntity>(
    _entities[0].properties[27],
  );

  /// See [MemoryEntity.isArchived].
  static final isArchived = obx.QueryBooleanProperty<MemoryEntity>(
    _entities[0].properties[28],
  );

  /// See [MemoryEntity.isConsolidated].
  static final isConsolidated = obx.QueryBooleanProperty<MemoryEntity>(
    _entities[0].properties[29],
  );

  /// See [MemoryEntity.contentHash].
  static final contentHash = obx.QueryStringProperty<MemoryEntity>(
    _entities[0].properties[30],
  );
}

/// [RawMessageEntity] entity fields to define ObjectBox queries.
class RawMessageEntity_ {
  /// See [RawMessageEntity.obId].
  static final obId = obx.QueryIntegerProperty<RawMessageEntity>(
    _entities[1].properties[0],
  );

  /// See [RawMessageEntity.uid].
  static final uid = obx.QueryStringProperty<RawMessageEntity>(
    _entities[1].properties[1],
  );

  /// See [RawMessageEntity.content].
  static final content = obx.QueryStringProperty<RawMessageEntity>(
    _entities[1].properties[2],
  );

  /// See [RawMessageEntity.source].
  static final source = obx.QueryStringProperty<RawMessageEntity>(
    _entities[1].properties[3],
  );

  /// See [RawMessageEntity.speakerId].
  static final speakerId = obx.QueryStringProperty<RawMessageEntity>(
    _entities[1].properties[4],
  );

  /// See [RawMessageEntity.petId].
  static final petId = obx.QueryStringProperty<RawMessageEntity>(
    _entities[1].properties[5],
  );

  /// See [RawMessageEntity.timestampMs].
  static final timestampMs = obx.QueryIntegerProperty<RawMessageEntity>(
    _entities[1].properties[6],
  );

  /// See [RawMessageEntity.isProcessed].
  static final isProcessed = obx.QueryBooleanProperty<RawMessageEntity>(
    _entities[1].properties[7],
  );

  /// See [RawMessageEntity.processedAtMs].
  static final processedAtMs = obx.QueryIntegerProperty<RawMessageEntity>(
    _entities[1].properties[8],
  );

  /// See [RawMessageEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<RawMessageEntity>(
    _entities[1].properties[9],
  );
}
